"""Initial migration

Revision ID: f99591cae2ed
Revises: 
Create Date: 2024-11-18 10:29:42.455399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99591cae2ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('todo_id', sa.UUID(), server_default=sa.text('uuid_generate_v1()'), nullable=False),
    sa.Column('todo_text', sa.TEXT(), nullable=False),
    sa.Column('todo_date', sa.DATE(), server_default=sa.text('CAST(now() AS DATE)'), nullable=False),
    sa.PrimaryKeyConstraint('todo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.execute('DROP EXTENSION "uuid-ossp";')
    # ### end Alembic commands ###
